(ns hitechcloud.sdk.client
  (:require [hitechcloud.sdk.http-client :as http]
            [hitechcloud.sdk.affiliate :as affiliate]
            [hitechcloud.sdk.affiliates_advanced :as affiliates_advanced]
            [hitechcloud.sdk.ai_factory :as ai_factory]
            [hitechcloud.sdk.auth :as auth]
            [hitechcloud.sdk.bare_metal :as bare_metal]
            [hitechcloud.sdk.billing :as billing]
            [hitechcloud.sdk.cart :as cart]
            [hitechcloud.sdk.ceph_s3 :as ceph_s3]
            [hitechcloud.sdk.cloud_gpu :as cloud_gpu]
            [hitechcloud.sdk.cloud_instance :as cloud_instance]
            [hitechcloud.sdk.cloud_service :as cloud_service]
            [hitechcloud.sdk.cloud_vm :as cloud_vm]
            [hitechcloud.sdk.collocation :as collocation]
            [hitechcloud.sdk.contacts :as contacts]
            [hitechcloud.sdk.dns :as dns]
            [hitechcloud.sdk.dns_manage :as dns_manage]
            [hitechcloud.sdk.domains :as domains]
            [hitechcloud.sdk.email_mfa_v2 :as email_mfa_v2]
            [hitechcloud.sdk.hosting :as hosting]
            [hitechcloud.sdk.ipam :as ipam]
            [hitechcloud.sdk.location_v2 :as location_v2]
            [hitechcloud.sdk.network_services :as network_services]
            [hitechcloud.sdk.notifications :as notifications]
            [hitechcloud.sdk.partner :as partner]
            [hitechcloud.sdk.passkey_v2 :as passkey_v2]
            [hitechcloud.sdk.pmg :as pmg]
            [hitechcloud.sdk.proxmox :as proxmox]
            [hitechcloud.sdk.proxmox_backup :as proxmox_backup]
            [hitechcloud.sdk.service_status :as service_status]
            [hitechcloud.sdk.services :as services]
            [hitechcloud.sdk.ssl :as ssl]
            [hitechcloud.sdk.support :as support]
            [hitechcloud.sdk.url_shortener :as url_shortener]
            [hitechcloud.sdk.users :as users]
            [hitechcloud.sdk.vcloudstack :as vcloudstack]
            [hitechcloud.sdk.virtualizor :as virtualizor]
            [hitechcloud.sdk.vneidekyc :as vneidekyc]
            [hitechcloud.sdk.will_expired :as will_expired]))

(defn make-client [& {:keys [base-url token timeout max-retries]
                       :or {base-url "https://api.hitechcloud.vn" timeout 30 max-retries 3}}]
  (let [http-client (http/make-client :base-url base-url :token token :timeout timeout :max-retries max-retries)]
    {:http http-client}))
