# frozen_string_literal: true

require_relative 'hitechcloud/version'
require_relative 'hitechcloud/exceptions'
require_relative 'hitechcloud/http_client'
require_relative 'hitechcloud/resources/base'
require_relative 'hitechcloud/resources/auth'
require_relative 'hitechcloud/resources/users'
require_relative 'hitechcloud/resources/services'
require_relative 'hitechcloud/resources/domains'
require_relative 'hitechcloud/resources/dns_manage'
require_relative 'hitechcloud/resources/dns'
require_relative 'hitechcloud/resources/ssl'
require_relative 'hitechcloud/resources/billing'
require_relative 'hitechcloud/resources/support'
require_relative 'hitechcloud/resources/contacts'
require_relative 'hitechcloud/resources/cart'
require_relative 'hitechcloud/resources/notifications'
require_relative 'hitechcloud/resources/affiliate'
require_relative 'hitechcloud/resources/cloud_gpu'
require_relative 'hitechcloud/resources/virtualizor'
require_relative 'hitechcloud/resources/cloud_service'
require_relative 'hitechcloud/resources/network_services'
require_relative 'hitechcloud/resources/service_status'
require_relative 'hitechcloud/resources/bare_metal'
require_relative 'hitechcloud/resources/collocation'
require_relative 'hitechcloud/resources/vcloudstack'
require_relative 'hitechcloud/resources/hosting'
require_relative 'hitechcloud/resources/location_v2'
require_relative 'hitechcloud/resources/cloud_instance'
require_relative 'hitechcloud/resources/cloud_vm'
require_relative 'hitechcloud/resources/affiliates_advanced'
require_relative 'hitechcloud/resources/ai_factory'
require_relative 'hitechcloud/resources/passkey_v2'
require_relative 'hitechcloud/resources/email_mfa_v2'
require_relative 'hitechcloud/resources/vneidekyc'
require_relative 'hitechcloud/resources/will_expired'
require_relative 'hitechcloud/resources/url_shortener'
require_relative 'hitechcloud/resources/proxmox_backup'
require_relative 'hitechcloud/resources/ceph_s3'
require_relative 'hitechcloud/resources/pmg'
require_relative 'hitechcloud/resources/proxmox'
require_relative 'hitechcloud/resources/ipam'
require_relative 'hitechcloud/resources/partner'
require_relative 'hitechcloud/client'

module HiTechCloud
  PRODUCTION_URL = 'https://api.hitechcloud.vn'
  OTE_URL = 'https://ote.hitechcloud.vn'
end
