//! HiTechCloud Client

use std::sync::Arc;
use crate::http_client::HttpClient;
use crate::*;

pub struct Client {
    http: Arc<HttpClient>,
    pub affiliate: AffiliateResource,
    pub affiliates_advanced: AffiliatesAdvancedResource,
    pub ai_factory: AiFactoryResource,
    pub auth: AuthResource,
    pub bare_metal: BareMetalResource,
    pub billing: BillingResource,
    pub cart: CartResource,
    pub ceph_s3: CephS3Resource,
    pub cloud_gpu: CloudGpuResource,
    pub cloud_instance: CloudInstanceResource,
    pub cloud_service: CloudServiceResource,
    pub cloud_vm: CloudVmResource,
    pub collocation: CollocationResource,
    pub contacts: ContactsResource,
    pub dns: DnsResource,
    pub dns_manage: DnsManageResource,
    pub domains: DomainsResource,
    pub email_mfa_v2: EmailMfaV2Resource,
    pub hosting: HostingResource,
    pub ipam: IpamResource,
    pub location_v2: LocationV2Resource,
    pub network_services: NetworkServicesResource,
    pub notifications: NotificationsResource,
    pub partner: PartnerResource,
    pub passkey_v2: PasskeyV2Resource,
    pub pmg: PmgResource,
    pub proxmox: ProxmoxResource,
    pub proxmox_backup: ProxmoxBackupResource,
    pub service_status: ServiceStatusResource,
    pub services: ServicesResource,
    pub ssl: SSLResource,
    pub support: SupportResource,
    pub url_shortener: UrlShortenerResource,
    pub users: UsersResource,
    pub vcloudstack: VCloudStackResource,
    pub virtualizor: VirtualizorResource,
    pub vneidekyc: VNeIdeKycResource,
    pub will_expired: WillExpiredResource,
}

impl Client {
    pub fn new(base_url: Option<&str>, token: Option<String>, timeout: Option<u64>, max_retries: Option<u32>) -> Self {
        let http = Arc::new(HttpClient::new(
            base_url.unwrap_or("https://api.hitechcloud.vn"),
            token,
            timeout.unwrap_or(30),
            max_retries.unwrap_or(3),
        ));
        Self {
            affiliate: AffiliateResource::new(http.clone()),
            affiliates_advanced: AffiliatesAdvancedResource::new(http.clone()),
            ai_factory: AiFactoryResource::new(http.clone()),
            auth: AuthResource::new(http.clone()),
            bare_metal: BareMetalResource::new(http.clone()),
            billing: BillingResource::new(http.clone()),
            cart: CartResource::new(http.clone()),
            ceph_s3: CephS3Resource::new(http.clone()),
            cloud_gpu: CloudGpuResource::new(http.clone()),
            cloud_instance: CloudInstanceResource::new(http.clone()),
            cloud_service: CloudServiceResource::new(http.clone()),
            cloud_vm: CloudVmResource::new(http.clone()),
            collocation: CollocationResource::new(http.clone()),
            contacts: ContactsResource::new(http.clone()),
            dns: DnsResource::new(http.clone()),
            dns_manage: DnsManageResource::new(http.clone()),
            domains: DomainsResource::new(http.clone()),
            email_mfa_v2: EmailMfaV2Resource::new(http.clone()),
            hosting: HostingResource::new(http.clone()),
            ipam: IpamResource::new(http.clone()),
            location_v2: LocationV2Resource::new(http.clone()),
            network_services: NetworkServicesResource::new(http.clone()),
            notifications: NotificationsResource::new(http.clone()),
            partner: PartnerResource::new(http.clone()),
            passkey_v2: PasskeyV2Resource::new(http.clone()),
            pmg: PmgResource::new(http.clone()),
            proxmox: ProxmoxResource::new(http.clone()),
            proxmox_backup: ProxmoxBackupResource::new(http.clone()),
            service_status: ServiceStatusResource::new(http.clone()),
            services: ServicesResource::new(http.clone()),
            ssl: SSLResource::new(http.clone()),
            support: SupportResource::new(http.clone()),
            url_shortener: UrlShortenerResource::new(http.clone()),
            users: UsersResource::new(http.clone()),
            vcloudstack: VCloudStackResource::new(http.clone()),
            virtualizor: VirtualizorResource::new(http.clone()),
            vneidekyc: VNeIdeKycResource::new(http.clone()),
            will_expired: WillExpiredResource::new(http.clone()),
            http: http.clone(),
        }
    }
}
