import 'http_client.dart';
import 'affiliate.dart';
import 'affiliates_advanced.dart';
import 'ai_factory.dart';
import 'auth.dart';
import 'bare_metal.dart';
import 'billing.dart';
import 'cart.dart';
import 'ceph_s3.dart';
import 'cloud_gpu.dart';
import 'cloud_instance.dart';
import 'cloud_service.dart';
import 'cloud_vm.dart';
import 'collocation.dart';
import 'contacts.dart';
import 'dns.dart';
import 'dns_manage.dart';
import 'domains.dart';
import 'email_mfa_v2.dart';
import 'hosting.dart';
import 'ipam.dart';
import 'location_v2.dart';
import 'network_services.dart';
import 'notifications.dart';
import 'partner.dart';
import 'passkey_v2.dart';
import 'pmg.dart';
import 'proxmox.dart';
import 'proxmox_backup.dart';
import 'service_status.dart';
import 'services.dart';
import 'ssl.dart';
import 'support.dart';
import 'url_shortener.dart';
import 'users.dart';
import 'vcloudstack.dart';
import 'virtualizor.dart';
import 'vneidekyc.dart';
import 'will_expired.dart';

class Client {
  final HttpClient httpClient;
  late final AffiliateResource affiliate;
  late final AffiliatesAdvancedResource affiliatesAdvanced;
  late final AiFactoryResource aiFactory;
  late final AuthResource auth;
  late final BareMetalResource bareMetal;
  late final BillingResource billing;
  late final CartResource cart;
  late final CephS3Resource cephS3;
  late final CloudGpuResource cloudGpu;
  late final CloudInstanceResource cloudInstance;
  late final CloudServiceResource cloudService;
  late final CloudVmResource cloudVm;
  late final CollocationResource collocation;
  late final ContactsResource contacts;
  late final DnsResource dns;
  late final DnsManageResource dnsManage;
  late final DomainsResource domains;
  late final EmailMfaV2Resource emailMfaV2;
  late final HostingResource hosting;
  late final IpamResource ipam;
  late final LocationV2Resource locationV2;
  late final NetworkServicesResource networkServices;
  late final NotificationsResource notifications;
  late final PartnerResource partner;
  late final PasskeyV2Resource passkeyV2;
  late final PmgResource pmg;
  late final ProxmoxResource proxmox;
  late final ProxmoxBackupResource proxmoxBackup;
  late final ServiceStatusResource serviceStatus;
  late final ServicesResource services;
  late final SSLResource ssl;
  late final SupportResource support;
  late final UrlShortenerResource urlShortener;
  late final UsersResource users;
  late final VCloudStackResource vcloudstack;
  late final VirtualizorResource virtualizor;
  late final VNeIdeKycResource vneidekyc;
  late final WillExpiredResource willExpired;

  Client({String? baseUrl, String? token, int timeout = 30, int maxRetries = 3}) {
    httpClient = HttpClient(baseUrl: baseUrl ?? 'https://api.hitechcloud.vn', token: token, timeout: timeout, maxRetries: maxRetries);
    affiliate = AffiliateResource(httpClient);
    affiliatesAdvanced = AffiliatesAdvancedResource(httpClient);
    aiFactory = AiFactoryResource(httpClient);
    auth = AuthResource(httpClient);
    bareMetal = BareMetalResource(httpClient);
    billing = BillingResource(httpClient);
    cart = CartResource(httpClient);
    cephS3 = CephS3Resource(httpClient);
    cloudGpu = CloudGpuResource(httpClient);
    cloudInstance = CloudInstanceResource(httpClient);
    cloudService = CloudServiceResource(httpClient);
    cloudVm = CloudVmResource(httpClient);
    collocation = CollocationResource(httpClient);
    contacts = ContactsResource(httpClient);
    dns = DnsResource(httpClient);
    dnsManage = DnsManageResource(httpClient);
    domains = DomainsResource(httpClient);
    emailMfaV2 = EmailMfaV2Resource(httpClient);
    hosting = HostingResource(httpClient);
    ipam = IpamResource(httpClient);
    locationV2 = LocationV2Resource(httpClient);
    networkServices = NetworkServicesResource(httpClient);
    notifications = NotificationsResource(httpClient);
    partner = PartnerResource(httpClient);
    passkeyV2 = PasskeyV2Resource(httpClient);
    pmg = PmgResource(httpClient);
    proxmox = ProxmoxResource(httpClient);
    proxmoxBackup = ProxmoxBackupResource(httpClient);
    serviceStatus = ServiceStatusResource(httpClient);
    services = ServicesResource(httpClient);
    ssl = SSLResource(httpClient);
    support = SupportResource(httpClient);
    urlShortener = UrlShortenerResource(httpClient);
    users = UsersResource(httpClient);
    vcloudstack = VCloudStackResource(httpClient);
    virtualizor = VirtualizorResource(httpClient);
    vneidekyc = VNeIdeKycResource(httpClient);
    willExpired = WillExpiredResource(httpClient);
  }
}
